let arrayOfBadIngredients = [
    'Alcohol Denat',
    'Benzyl Alcohol',
    'Isopropyl Alcohol',
    'Ethanol Alcohol',
    'Propylene Glycol',
    'PEG',
    'PPG',
    'Sodium Lauryl Sulfate',
    'Sodium Laureth Sulfate',
    'Methylchloroisothiazolinone',
    'Formaldehyde',
    'Phenyl Dimethicone',
    'Phenyl Benzoate',
    'Imidiazolidynyl Urea',
    'Diazolidynyl Urea',
];
let arrayOfProteins = [
    'Hydrolyzed Silk',
    'Hydrolyzed Keratin',
    'Keratin',
    'Hydrolyzed Wheat Protein',
    'Hydroxypropyltrimonium Hydrolyzed Wheat Protein',
    'Hydrolyzed Milk Protein',
    'Hydrolyzed Soya Protein',
    'Hydrolyzed Oat Protein',
    'Hydrolyzed Oats',
    'Protein',
    'Elastin',
    'Collagen',
];
let arrayOfHumectants = [
    'Glycerin',
    'Urea',
    'Mel Extract',
    'Honeyquat',
    'Aloe Vera',
    'Aloe Barbadensis Leaf Juice',
    'Fructose',
    'Xylitol',
    'Dexpanthenol',
    'Tocopheryl Acetate',
    'Urtica Dioica Leaf Extract',
    'Betaine',
];
let arrayOfEmolients = [
    'Lanolin',
    'Rosa Canina Fruit Oil',
    'Rice Bran Oil',
    'Butter',
    'Shea Butter',
    'Butyrospermum Parkii Butter',
    'Prunus Amygdalus Dulcis Oil',
    'Cera Alba',
    'Squalane',
    'Paraffinum Liquidum',
    'Cetyl Alkohol',
    'Cetearyl Alkohol',
    'Oil',
    'Dimethiconol',
    'Polydimethylsiloxane',
    'Cyclopentasiloxane',
    'Trimethylsilylamodimethicone',
    'Amodimethicone',
    'Cyclomethicone',
    'Trimethicone',
    'Methicone',
    'Dimethicone',
    'Sorbitan Stearate',
    'Cucumis Sativus Fruit Extract',
    'Helianthus Annuus Extract',
];

let questions = [
    new Question('1. Does your hair tend to curl?', [
        'No, they are completely straight',
        'Medium, gently undulating or only at the ends',
        'Yes, they are clearly wavy',
        'Yes, they are curly',
    ]),
    new Question('2. Is your hair frizzy?', [
        "No, I don't have that problem",
        'With proper styling, they do not frizz',
        'It happens that sometimes they frizzy',
        'Yes',
    ]),
    new Question('3. Is coconut oil good for your hair?', [
        'Yes, it works great',
        "It's hard to say, it's not working well or bad",
        'It works badly, it flushes or stiffens the hair',
        "I don't know",
    ]),
    new Question('4. Does your hair like hydrolyzed keratin?', [
        "Yes, it's very hard and it's hard to recycle them",
        "No, I don't have that problem",
        'Yes, but they can be reprocessed',
        'Difficult to say / do not use',
    ]),
    new Question('5.Does your hair like plant proteins?', [
        'Difficult to say / not apply',
        'No, they push or have a bad effect or no effect',
        'Yes!',
        'I have no idea',
    ]),
    new Question('6.Does glycerin fuzzy your hair ?', [
        "It doesn't fluff, I don't see the impact.",
        'it happens that it fluff - depends on the day / weather',
        "It has no effect, I don't have to avoid",
        'Yes, I fluff and I avoid it.',
    ]),
    new Question('7. How long does your hair dry?', [
        'They dry quickly, they are already dry practically immediately after washing',
        'They dry quickly because they are thin or there are not many of them',
        'They dry for a long time, but are dry in a few hours',
        "They don't dry for a long time, practically by themselves",
    ]),
    new Question('8. Do you lighten your hair or chemically dye your hair?', [
        'no',
        'once, not now',
        'a few time a year',
        'yes, regularly',
    ]),
    new Question('9. Do you use henna on your hair?', [
        'no',
        'I used to use it',
        'no, I use other herbal coloring agents: cassia, senna, indigo',
        'yes',
    ]),
    new Question('10. Is your hair amenable to styling?', [
        'They are susceptible, but not to every type of styling, or they recover quickly',
        "Yes, it's very easy to style, twist them",
        'No, they are very resistant to styling',
        'They are naturally curly',
    ]),
    new Question('11. Is your hair smooth, shiny, loose?', [
        'Yes, they are like a sheet',
        'They are smooth and loose, but do not create a glass effect',
        "They're curly but smooth and shiny",
        'They are quite rough, do not form a sheet',
    ]),
    new Question('12. Does your hair tend to get dry?', [
        'no',
        "I didn't notice",
        'It happens from time to time',
        'yes',
    ]),
    new Question('13. Does your hair like leave-in conditioners?', [
        'Yes, very often',
        'conditioners weigh them down',
        "It's hard to say / I don't see the need for using it",
        'I use a little, only for the ends',
    ]),
    new Question('14. Is your hair puffing out?', [
        "No, I don't have that problem",
        "Sometimes they pod, but it's not a big problem",
        "Yes, but it's curls so that's what I mean",
        'Yes, they pod and I have to comb them a lot',
    ]),
    new Question('15. Does your hair get clumpy?', [
        "Yes, I'm still fighting for volume!",
        'It happens or they are heavy for 2-3 days',
        "nie zauważyłam / łemI haven't noticed",
        'never',
    ]),
    new Question('16. You can describe your hair as ...', [
        'Light as a feather, delicate',
        'normal',
        'Medium thickness',
        'Heavy, thick',
    ]),
    new Question('17. The key favorite pillar of PEH for your hair is: ', [
        'proteins',
        'humectants',
        'emolients',
        'I do not know',
    ]),
];
